apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- echoserver-deployment.yaml
- echoserver-ingress.yaml
- echoserver-namespace.yaml
- echoserver-service.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: echoserver
  path: ingress_patch.json

